language: node_js

node_js:
  - "8.9.4"

before_install:
  - npm install -g babel-cli
  - npm install -g nearley

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libsecret-1-dev